exports.states = [{
    state: 'Kerala',
    districts: [
        { title: 'Kasaragod' },
        { title: 'Kannur' },
        { title: 'Kozhikode' },
        { title: 'Wayanad' },
        { title: 'Malappuram' },
        { title: 'Thrissur' },
        { title: 'Palakkad' },
        { title: 'Ernakulam' },
        { title: 'Idukki' },
        { title: 'Alappuzha' },
        { title: 'Kottayam' },
        { title: 'Pathanamthitta' },
        { title: 'Kollam' },
        { title: 'Thiruvananthapuram' },
    ]
}, {
    state: 'Karnataka',
    districts: [
        { title: 'Belagavi' },
        { title: 'Bengaluru Urban' },
        { title: 'Bengaluru Rural' },
        { title: 'Bidar' },
        { title: 'Vijayapura' },
        { title: 'Chamarajanagar' },
        { title: 'Chikkaballapur' },
        { title: 'Chikkamagaluru' },
        { title: 'Chitradurga' },
        { title: 'Dakshina Kannada' },
        { title: 'Davanagere' },
        { title: 'Dharwad' },
        { title: 'Gadag' },
        { title: 'Kalaburagi' },
        { title: 'Hassan' },
        { title: 'Haveri' },
        { title: 'Kodagu' },
        { title: 'Kolar' },
        { title: 'Koppal' },
        { title: 'Mandya' },
        { title: 'Mysuru' },
        { title: 'Raichur' },
        { title: 'Ramanagara' },
        { title: 'Shivamogga' },
        { title: 'Tumakuru' },
        { title: 'Udupi' },
        { title: 'Uttara Kannada' },
        { title: 'Yadgir' }
    ]
}]