export const endpoints = {
  validateEmail: "/validate-login",
  login: "/email-login",
  verifyEmail: "/verify",
  verifyEmailToken: "/verify-email",
  updateProfile: `/update-profile`,
  orders: `/orders`,
  emailLogin: "/email-login",
  guestLogin: "guest-login",
  continueasGuest: "continue-as-guest",
  register: "/register",
  forgotPassword: "/forgot-password",
  reorder: "reorder",
  about: `/about`,
  addAddress: `/add-address`,
  address: `/address`,
  addressDetails: `/address-details`,
  addReview: `/add-review`,
  addToCart: `/add-to-cart`,
  BuyNow: `/buy-now`,
  addToken: `/add-token`,
  addEnquiry: `/add-enquiry`,
  applyCoupon: `/apply-coupon`,
  blogs: `/blogs`,
  relatedBlogs:'/related-blogs',
  brands: `/brands`,
  categories: `/featured-categories`,
  categoryBySlug:`/category-by-slug`,
  categoriesList:'/categories',
  cart: `/cart`,
  count:'/counts',
  clearCart: `/clear-cart`,
  clickPoints: `/click-points`,
  chooseDefault: `/choose-default`,
  clearHistory: `/clear-history`,
  checkout: `/checkout`,
  codDetails: `/cod-details`,
  collections: `/collections`,
  collectionBySlug:`/collection-by-slug`,
  coupons: `/coupons`,
  deliveryTime: `/deliveryslots`,
  faq: `/faq`,
  footer: `/footer`,
  giftCardPurchase: `/purchase-voucher `,
  giftCardPurchaseHistory: `/purchase-history`,
  giftCartRedeem: `/redeem-voucher`,
  helpCenter: `/help-center`,
  home: `/dashboard`,
  logout: `/logout`,
  loyalityHistory: `/loyalty-history`,
  menu: `/mega-categories`,
  manageWishList: `/manage-wishlist`,
  manageGift: `/manage-gift`,
  notifications: `/notifications`,
  notifyme: `/stock-subscription`,
  offers: `/offers`,
  orderDetails: `/order-details`,
  placeOrder: `/place-order`,
  product: `/product`,
  privacy: `/privacy`,
  pageContents: "page-contents",
  productAttributes: `/product-attributes`,
  productsByCategory: `/product-listing`,
  productFilters:`product-filters`,
  productDetails: `/product-details`,
  popup: `/popup-details`,
  resetPassword: `/reset-password`,
  return: `/return`,
  returnProduct: `/return-request`,
  replaceProduct: `/replace-request`,
  removeFromCart: `/remove-from-cart`,
  removeCoupon: `/remove-coupon`,
  stores: `/stores`,
  searchProducts: `/search-products`,
  searchSuggestions: `/get-suggestions?search=`,
  popularSearch:'/popular-search',
  serviceWarrenty: `/service-warranty`,
  shipping: `/shipping-policy`,
  paymentPolicy: `/payment`,
  subCategories: `/subcategories`,
  sendOtp: `/send-otp`,
  verifyEmailaddress:`/verify-emailaddress`,
  varifyEmailOtp:`/varify-email-otp`,
  addressLocations:`/get-addresslocations`,
  locationDetails:`/get-locationdetails`,
  terms: `/terms`,
  theme: `/settings`,
  uploadMedia: `/upload-media`,
  googleLogin: `/google-login`,
  facebookLogin: `/facebook-login`,
  deleteMedia: `/delete-media`,
  updateCart: `/update-cart`,
  updateAddress: `/update-address?action=update`,
  deleteAddress: `/update-address?action=delete`,
  setAsDefaultAddress: `/update-address?action=manage`,
  subscribe: `/subscribe-newsletter`,
  unsubscribe: `/unsubscribe-newsletter`,
  user: `/user`,
  userProfile: `/user-details`,
  users: `/users`,
  validateOtp: `/validate-otp`,
  validateUser: `/validate-user`,
  verifySubscription: "/verify-subscription",
  dashboard: "/dashboard",
  catalogDetails: `catalog-details`,
  wishlist: "wishlist",
  verifyPayment: "/verify-payment",
  wallet: "/wallet-transactions",
  previewWidgets: "/preview-widgets",
  draftWidgets: "/draft-widgets",
  publishedWidgets: "/published-widgets",
  moreOffers: `/moreoffers`,
  moreOffersListing: `/moreoffers-listing`,
  createGuest: "/create-guest",
  guestCustomerDetails: "/guest-details",
  contactUs: `contact-us`,
  testimonials: `/testimonials`,
  advancedMenu: `/advancedcs-menu`,
  staticpage: "/staticpage",
  paymentGateWays: "/paymentgateways",
  products: `/products`,
  brandProducts: `/search-products`,
  seoDetails: `seodetails`,
  pagecovers: `/pagecovers`,
  productdesigns: `/productdesigns`,
  storetimer: `/storetimer`,
  shippingdetails: `/shipping-details`,
  shippingrule: `/shipping-rule`,
  websitemenu: `/website-menubar`,
  analytics: `/analytics`,
  pickupLocations: `/pickup-locations`,
  internationlisation: `/internationlisation`,
  updateUser: `/update-user`,
  updateGuest: `/update-guest`,
  getCurrentLocation: `/get-currentlocation`,
  getAddressLocations: `/get-addresslocations`,
  getLocationDetails: `/get-locationdetails`,
  verifyGuest: `/verify-guest`,
  submitProductEnquiry: `/submit-productenquiry`,
  getHeaderMenu: `/mega-categories`,
  getSideMenu : `/website-menubar`,
  socialmedia:`/get-socials`,
  applyGiftWrap: `/appy-gift-wrap`,
  removeGiftWrap: `/remove-gift-wrap`,
  getGiftWrapDetails: `/giftwrap-details`,
  categoryLandingPage: `/category-landing`,
  getCategoryDetails: `/get-all-categories`,
  getFooterData: `/footer-details`,
    addDeliveryNote:`/add-delivery-note`,
  removeDeliveryNote:`/remove-delivery-note`,
  getDeliveryNoteDetails:`/delivery-note-details`,
  updateCustomerLogoutTime:`/update-logouttime`,
  getAbout:`/about`,
  getSeoDetails:`/settings-details`,




  
};
